From centos
MAINTAINER test dev <test@dev.com>
run yum install epel-release
run yum install nginx 
VOLUME [ "/data" ,"/usr/local/bin/nginx"]

WORKDIR /etc/nginx

WORKDIR /root
RUN touch hello.txt

WORKDIR /tmp
RUN touch hello.txt
CMD [ "nginx" ]